### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Sogl** [jgrocha/GeoDashBoard#2]
Hello!

Can you provide a small installation instruction? 
Do I need to use `sencha cmd` for it or just `git clone` to webserver directory?

**Comment by jgrocha** [comment]
Hi @Sogl,

The initial idea was to provide sample code for developers. But it makes sense to improve the documentation regarding the installation. I'll add instructions to install the application. 

The application has a running demo available at [http://geodashboard.geomaster.pt/](http://geodashboard.geomaster.pt/)

**Comment by Sogl** [comment]
@jgrocha I'm new in ExtJS 6 version and OL3, but I need to create GPS tracking application. Your help is much appreciated.

I saw the demo, thank you for this work.

p.s. Maybe you encountered the similar thing? 
https://github.com/geoext/geoext3/issues/161

**Comment by Sogl** [comment]
@jgrocha Any progress on this? :wink:

**Comment by jgrocha** [comment]
I've update the [Readme.md](https://github.com/jgrocha/GeoDashBoard/blob/master/Readme.md) file with hints regarding the installation.
